In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from matplotlib.gridspec import GridSpec
from plotly.offline import iplot, init_notebook_mode
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

In [23]:
data2019 = pd.read_csv('../data/raw/microdados_matriculas_2019.csv', sep=';')
data2019.head()

,Teste,Carga Horaria,Carga Horaria Minima,Categoria da Situação,Código do Ciclo Matricula,Código da Matricula,Código da Unidade de Ensino - SISTEC,Cod Unidade,Cor / Raça,Data de Inicio do Ciclo,...,Vagas Extraordinárias l9,Vagas Regulares AC,Vagas Regulares l10,Vagas Regulares l13,Vagas Regulares l14,Vagas Regulares l1,Vagas Regulares l2,Vagas Regulares l5,Vagas Regulares l6,Vagas Regulares l9
0,1,4535,3600,Concluintes,1978481,64063592,3483,147,Não declarada,20/02/2015,...,0.0,17.0,0.0,0.0,0.0,2.0,7.0,2.0,7.0,0.0
1,1,4535,3600,Em curso,1978481,64063608,3483,147,Não declarada,20/02/2015,...,0.0,17.0,0.0,0.0,0.0,2.0,7.0,2.0,7.0,0.0
2,1,4535,3600,Em curso,1978481,64063640,3483,147,Não declarada,20/02/2015,...,0.0,17.0,0.0,0.0,0.0,2.0,7.0,2.0,7.0,0.0
3,1,4535,3600,Em curso,1978481,64063638,3483,147,Não declarada,20/02/2015,...,0.0,17.0,0.0,0.0,0.0,2.0,7.0,2.0,7.0,0.0
4,1,4535,3600,Em curso,1978481,64063630,3483,147,Não declarada,20/02/2015,...,0.0,17.0,0.0,0.0,0.0,2.0,7.0,2.0,7.0,0.0

In [24]:
data2020 = pd.read_csv('../data/raw/microdados_matriculas_2020.csv', sep=';')
data2020.head()

,Carga Horaria,Carga Horaria Minima,Categoria de Situação,Cod Unidade,Cor/Raça,Código da Matrícula,Código da Unidade de Ensino - SISTEC,Código do Ciclo de Matrícula,Código do Município com DV,Data de Fim Previsto do Ciclo,...,Vagas Ofertadas,Vagas Regulares AC,Vagas Regulares l1,Vagas Regulares l10,Vagas Regulares l13,Vagas Regulares l14,Vagas Regulares l2,Vagas Regulares l5,Vagas Regulares l6,Vagas Regulares l9
0,3182,800,Concluintes,17,BRANCA,66845709,13791,2016192,5201108,20/12/2018,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,3641,1200,Concluintes,279,BRANCA,66801823,3508,2016354,5211503,20/12/2018,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5800,4000,Concluintes,523,BRANCA,64271041,2956,1859227,5221809,21/12/2018,...,40.0,20.0,3.0,1.0,1.0,1.0,5.0,3.0,5.0,1.0
3,4370,3600,Evadidos,523,BRANCA,44608044,2956,1206840,5221809,22/12/2016,...,40.0,20.0,3.0,1.0,1.0,1.0,5.0,3.0,5.0,1.0
4,5800,4000,Concluintes,523,BRANCA,59220389,2956,1859227,5221809,21/12/2018,...,40.0,20.0,3.0,1.0,1.0,1.0,5.0,3.0,5.0,1.0

In [25]:
data2021 = pd.read_csv('../data/raw/microdados_matriculas_2021.csv', sep=';', encoding='utf-8')
data2021.head()

,Carga Horaria,Carga Horaria Mínima,Categoria da Situação,Co Inst,Cod Unidade,Cor / Raça,Código da Matricula,Código da Unidade de Ensino - SISTEC,Código do Ciclo Matricula,Código do Município com DV,...,Vagas Ofertadas,Vagas Regulares AC,Vagas Regulares l1,Vagas Regulares l10,Vagas Regulares l13,Vagas Regulares l14,Vagas Regulares l2,Vagas Regulares l5,Vagas Regulares l6,Vagas Regulares l9
0,200,200.0,Evadidos,262432,557,Amarela,96176470,3479.0,2716099,2407104,...,850.0,850.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,160,160.0,Em curso,26436,6002,Amarela,102483972,45430.0,2830452,4314407,...,2834.0,2834.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,160,160.0,Em curso,26436,6002,Amarela,102459282,45430.0,2830437,4314407,...,1234.0,1234.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,40,160.0,Em curso,26419,116,Amarela,97887414,2936.0,2745532,4302105,...,265.0,265.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1380,1200.0,Em curso,26404,436,Amarela,91646798,2947.0,2632269,2927903,...,40.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [144]:
data2019.columns

Index(['Carga Horária', 'Categoria da Situação', 'Cor/Raça',
       'Código da Matrícula', 'Data de Fim Previsto do Ciclo',
       'Data de Início do Ciclo', 'Data de Ocorrência da Matrícula',
       'Eixo Tecnológico', 'Faixa Etária', 'Fator Esforço Curso', 'Idade',
       'Instituição', 'Nome de Curso', 'Região', 'Renda Familiar', 'Sexo',
       'Situação de Matrícula', 'Tipo de Curso', 'Turno', 'UF',
       'Unidade de Ensino'],
      dtype='object')

In [59]:
data2019.drop(columns=['Teste', 'Carga Horaria Minima', 'Código do Ciclo Matricula',
'Código da Unidade de Ensino - SISTEC', 'Cod Unidade', 'Total de Inscritos','Modalidade de Ensino',
'Código do Município com DV', 'Vagas Ofertadas', 'Sub Eixo Tecnologico', 'Tipo Oferta', 'Mês De Ocorrência da Situação',
'Vagas Extraordinárias AC', 'Vagas Extraordinárias l10', 'Fonte de Financiamento', 'Município ', 'Número de registros',
'Vagas Extraordinárias l13', 'Vagas Extraordinárias l14',
'Vagas Extraordinárias l1', 'Vagas Extraordinárias l2',
'Vagas Extraordinárias l5', 'Vagas Extraordinárias l6',
'Vagas Extraordinárias l9', 'Vagas Regulares AC', 'Vagas Regulares l10',
'Vagas Regulares l13', 'Vagas Regulares l14', 'Vagas Regulares l1',
'Vagas Regulares l2', 'Vagas Regulares l5', 'Vagas Regulares l6',
'Vagas Regulares l9'],axis=1, inplace=True)

In [150]:
data2020.columns

Index(['Carga Horária', 'Categoria da Situação', 'Cor/Raça',
       'Código da Matrícula', 'Data de Fim Previsto do Ciclo',
       'Data de Início do Ciclo', 'Data de Ocorrência da Matrícula',
       'Eixo Tecnológico', 'Faixa Etária', 'Fator Esforço Curso', 'Idade',
       'Instituição', 'Nome de Curso', 'Região', 'Renda Familiar', 'Sexo',
       'Situação de Matrícula', 'Tipo de Curso', 'Turno', 'UF',
       'Unidade de Ensino'],
      dtype='object')

In [149]:
nomes2020 = { 'Carga Horaria': 'Carga Horária', 'Data de Inicio do Ciclo':'Data de Início do Ciclo', 'Fator Esforco Curso': 'Fator Esforço Curso', 'Categoria de Situação': 'Categoria da Situação'}
data2020 = data2020.rename(columns=nomes2020)

In [65]:
data2020.drop(columns=['Carga Horaria Minima', 'Código do Ciclo de Matrícula',
'Código da Unidade de Ensino - SISTEC', 'Cod Unidade', 'Modalidade de Ensino',
'Código do Município com DV', 'Fonte de Financiamento', 'Vagas Ofertadas', 'Subeixo Tecnológico', 'Tipo Oferta', 'Tipo de Oferta', 'Matrícula 2019', 'Número de registros', 'Subeixo Tecnológico',
'Vagas Extraordinárias AC', 'Vagas Extraordinárias l10','Mês de Ocorrência da Situação', 'Tipo de Unidade',
'Vagas Extraordinárias l13', 'Vagas Extraordinárias l14',
'Vagas Extraordinárias l1', 'Vagas Extraordinárias l2',
'Vagas Extraordinárias l5', 'Vagas Extraordinárias l6',
'Vagas Extraordinárias l9', 'Vagas Regulares AC', 'Vagas Regulares l10',
'Vagas Regulares l13', 'Vagas Regulares l14', 'Vagas Regulares l1',
'Vagas Regulares l2', 'Vagas Regulares l5', 'Vagas Regulares l6',
'Vagas Regulares l9'],axis=1, inplace=True)

In [137]:
data2021.columns

Index(['Carga Horária', 'Categoria da Situação', 'Cor/Raça',
       'Código da Matrícula', 'Data de Fim Previsto do Ciclo',
       'Data de Início do Ciclo', 'Data de Ocorrência da Matrícula',
       'Eixo Tecnológico', 'Faixa Etária', 'Fator Esforço Curso', 'Idade',
       'Instituição', 'Nome de Curso', 'Região', 'Renda Familiar', 'Sexo',
       'Situação de Matrícula', 'Tipo de Curso', 'Turno', 'UF',
       'Unidade de Ensino'],
      dtype='object')

In [154]:
nomes2021 = { 'Carga Horaria': 'Carga Horária', 'Cor / Raça': 'Cor/Raça', 'Código da Matricula': 'Código da Matrícula', 'Data de Inicio do Ciclo':'Data de Início do Ciclo', 
             'Fator Esforco Curso': 'Fator Esforço Curso', 'Data de Ocorrência da Matrícula:': 'Data de Ocorrência da Matrícula'}
data2021 = data2021.rename(columns=nomes2021)

In [72]:
data2021.drop(columns=['Carga Horaria Mínima', 'Código do Ciclo Matricula', 'Número de registros', 'Co Inst', 'Matrículas Atendida',
'Código da Unidade de Ensino - SISTEC', 'Cod Unidade', 'Modalidade de Ensino', 'Mês De Ocorrência da Situação', 'Código do Ciclo Matricula',
'Código do Município com DV', 'Fonte de Financiamento', 'Vagas Ofertadas', 'Subeixo Tecnológico',  'Tipo de Oferta', 'Total de Inscritos',
'Vagas Extraordinárias AC', 'Vagas Extraordinárias l10', 'Matrículas Equivalentes', 'Município'
'Vagas Extraordinárias l13', 'Vagas Extraordinárias l14',
'Vagas Extraordinárias l1', 'Vagas Extraordinárias l2',
'Vagas Extraordinárias l5', 'Vagas Extraordinárias l6',
'Vagas Extraordinárias l9', 'Vagas Regulares AC', 'Vagas Regulares l10',
'Vagas Regulares l13', 'Vagas Regulares l14', 'Vagas Regulares l1',
'Vagas Regulares l2', 'Vagas Regulares l5', 'Vagas Regulares l6',
'Vagas Regulares l9'],axis=1, inplace=True)

In [143]:
nomes2019 = { 'Cor / Raça': 'Cor/Raça', 'Código da Matricula': 'Código da Matrícula', 'Data de Inicio do Ciclo':'Data de Início do Ciclo',
'Data de Ocorrência da Matrícula:': 'Data de Ocorrência da Matrícula', 'Região ': 'Região', 'UF ':'UF'}
data2019 = data2019.rename(columns=nomes2019)

In [124]:
nomes2019 = { 'Carga Horária ' : 'Carga Horária'}
data2019 = data2019.rename(columns=nomes2019)

In [151]:
novo_dataset = pd.concat ([data2019, data2020, data2021])

In [152]:
novo_dataset

,Carga Horária,Categoria da Situação,Cor/Raça,Código da Matrícula,Data de Fim Previsto do Ciclo,Data de Início do Ciclo,Data de Ocorrência da Matrícula,Eixo Tecnológico,Faixa Etária,Fator Esforço Curso,...,Instituição,Nome de Curso,Região,Renda Familiar,Sexo,Situação de Matrícula,Tipo de Curso,Turno,UF,Unidade de Ensino
0,4535,Concluintes,Não declarada,64063592,20/12/2019,20/02/2015,01/02/2015,Recursos Naturais,20 a 24 anos,"1,15",...,IFMT,Agronomia,Região Centro-Oeste,Não Declarada,Masculino,Concluída,Bacharelado,Integral,MT,Campus Campo Novo do Parecis
1,4535,Em curso,Não declarada,64063608,20/12/2019,20/02/2015,01/02/2015,Recursos Naturais,20 a 24 anos,"1,15",...,IFMT,Agronomia,Região Centro-Oeste,Não Declarada,Masculino,Em curso,Bacharelado,Integral,MT,Campus Campo Novo do Parecis
2,4535,Em curso,Não declarada,64063640,20/12/2019,20/02/2015,01/02/2015,Recursos Naturais,30 a 34 anos,"1,15",...,IFMT,Agronomia,Região Centro-Oeste,Não Declarada,Masculino,Em curso,Bacharelado,Integral,MT,Campus Campo Novo do Parecis
3,4535,Em curso,Não declarada,64063638,20/12/2019,20/02/2015,01/02/2015,Recursos Naturais,20 a 24 anos,"1,15",...,IFMT,Agronomia,Região Centro-Oeste,Não Declarada,Masculino,Em curso,Bacharelado,Integral,MT,Campus Campo Novo do Parecis
4,4535,Em curso,Não declarada,64063630,20/12/2019,20/02/2015,01/02/2015,Recursos Naturais,20 a 24 anos,"1,15",...,IFMT,Agronomia,Região Centro-Oeste,Não Declarada,Masculino,Em curso,Bacharelado,Integral,MT,Campus Campo Novo do Parecis
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1523341,20,Concluintes,Não declarada,96122031,01/12/2020,01/09/2020,01/09/2020,Desenvolvimento Educacional e Social,S/I,"1,1",...,IF FARROUPILHA,Qualificação Profissional - Desenvolvimento Ed...,Região Sul,Não declarada,S/I,Concluída,Qualificação Profissional (FIC),Não se aplica,RS,Campus Panambi
1523342,20,Concluintes,Não declarada,96122037,01/12/2020,01/09/2020,01/09/2020,Desenvolvimento Educacional e Social,S/I,"1,1",...,IF FARROUPILHA,Qualificação Profissional - Desenvolvimento Ed...,Região Sul,Não declarada,S/I,Concluída,Qualificação Profissional (FIC),Não se aplica,RS,Campus Panambi
1523343,160,Evadidos,Parda,95091099,30/09/2020,01/06/2020,01/06/2020,Informação e Comunicação,S/I,"1,1",...,IFSUL,Montador e Reparador de Computadores,Região Sul,"0,5<RFP<=1,0",S/I,Abandono,Qualificação Profissional (FIC),Não se aplica,RS,Campus Passo Fundo
1523344,200,Evadidos,Parda,95087323,30/09/2020,01/06/2020,01/06/2020,Informação e Comunicação,S/I,"1,1",...,IFSUL,Programador Web,Região Sul,"0,5<RFP<=1,0",S/I,Abandono,Qualificação Profissional (FIC),Não se aplica,RS,Campus Camaquã
1523345,180,Evadidos,Preta,95103817,30/09/2020,01/06/2020,01/06/2020,Gestão e Negócios,S/I,"1,1",...,IFSUL,Qualificação Profissional - Gestão e Negócios,Região Sul,"0<RFP<=0,5",S/I,Abandono,Qualificação Profissional (FIC),Não se aplica,RS,Centro de Referência Pelotas

In [161]:
novo_dataset ['Categoria da Situação'].unique()

array(['Concluintes', 'Em curso', 'Evadidos'], dtype=object)

In [153]:
novo_dataset.columns

Index(['Carga Horária', 'Categoria da Situação', 'Cor/Raça',
       'Código da Matrícula', 'Data de Fim Previsto do Ciclo',
       'Data de Início do Ciclo', 'Data de Ocorrência da Matrícula',
       'Eixo Tecnológico', 'Faixa Etária', 'Fator Esforço Curso', 'Idade',
       'Instituição', 'Nome de Curso', 'Região', 'Renda Familiar', 'Sexo',
       'Situação de Matrícula', 'Tipo de Curso', 'Turno', 'UF',
       'Unidade de Ensino'],
      dtype='object')

In [162]:
novo1 = novo_dataset[novo_dataset['Tipo de Curso']=='Ensino Médio']

In [163]:
novo2 = novo1[(novo1['Categoria da Situação']=='Concluintes')|(novo1['Categoria da Situação']=='Evadidos')]

In [166]:
novo3 = novo2.dropna()

In [169]:
novo3[novo3.duplicated()]

Empty DataFrame
Columns: [Carga Horária, Categoria da Situação, Cor/Raça, Código da Matrícula, Data de Fim Previsto do Ciclo, Data de Início do Ciclo, Data de Ocorrência da Matrícula, Eixo Tecnológico, Faixa Etária, Fator Esforço Curso, Idade, Instituição, Nome de Curso, Região, Renda Familiar, Sexo, Situação de Matrícula, Tipo de Curso, Turno, UF, Unidade de Ensino]
Index: []

[0 rows x 21 columns]

In [172]:
duplicados = novo3[novo3['Código da Matrícula'].duplicated()]

In [173]:
novo4 = novo3.drop_duplicates(subset=['Código da Matrícula'])

In [178]:
novo4.to_csv(index=False, path_or_buf='prepocessing.csv')